title: Gimer Cervera # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. in Computer Science granted by Carleton University (2012)
  Ottawa, ON. Canada.
  <br><br>
  Computer science geek and a passionate about Blockchain technology!
  <br><br>
  View my
  <a href="https://certificates.b9lab.com/certificate.html?uuid=b09ea6db-cb52-4e2d-8cec-d7a9dd64d5b0" target="_blank">
  Ethereum Developer Certificate
  </a>
  <br>
  ### Contact Information
  <br>
  <a href="https://www.linkedin.com/in/gimercervera/" target="_blank">View My LinkedIn Profile</a>
  <br>
  website: <a href="https://dappdojo.com" target="_blank">https://dappdojo.com</a>
  <br>
  email: gimer@dappdojo.com
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
